language: go
go:
- 1.8
env:
  global:
  - secure: WkVNkFzk7rYTun8QTZEHjrfICL1QuoiE2+fqwKEGdgZGAuqAXEzbST+pL3D1mrmxjX5Z7a2e9/Del6B5M4iaYU2+LZAdlJMHbKW3Vw7HzzFCJp5NrOksqASWNT2foRGgjr4SO3kwbH0Fazu8d3CgkF8sKqojoh0L5qgM1f5aTHfDzU2OqpvTEPOaNcOvUi3U6TmEoA0hCmg7xlDsE8/CIoPe1dO1sJ7h0kkSq7LKcvtNYdjqdPznuOWyG7rYcVtqpUjWmuM2knuU8al2SXEioLrurAFIC+xo2ExcMVCfnd+PIgJHKOqcGmxoUvJr+Af7U7+USFuhazZjChIPBG0v2VVA8F2Gfnabwq0yFis2GJ6AxupAbdx2ly86LeFS7qiO0g/uizUkM4AaJ8usGX4odvxTwhYKzoV55cvvPjkf7DIwIcLayc2pjLB0G30ktOAmedJYhGTwY55ROUGc9F65eBqP6Y9oceB2bvBovSybt2JiwvFcG4YSuakGQociN68uEPMc5N0yKAVdPqkPY3scTcI+eGZ0e+Odf9FQa60hCB6TGaebtw6ovIuf/hlgCdLX/Pc50atxe362Mh1fCe09iBFMhNzfh8wR2kjDnDcKUAelUW/bD4mE58uFQkCNrjP5Fn6eVJlSd2Us+P6F49O0Rh9MrzdQDcjgWO90aX6PqNU=
  - secure: DDX6qtz4TmP6upCmwMSEmHBPqrdmwWvw/NzP23PU7w2PWIetiucUxPg06xDMATUd+nh8riZxBeWMRVnzVyY5M0ddHtbCSLxn/OMIQBsmq/hkF/B1EmtDlMkOOO+H0vqUq0POELMjSp+Tk2zK8RGBLKeBQNyYGZhuoNrfjEfu3uzybGxApEoo7E1gdhcdy/wErVSA29TNUOg/uq/by6APa/dp2EcCQvaZ3P6aZHlyeHGGnGaPL/T/40gdcTyU435OEozK+nheFnFU8xw2akctAMJkWQLipZCAPw233Qa4vicvt3mRpOVB/l9IJHzq7BRGy1i8BvwPMJKPDFWFWW5U9/wYgF/tdjPsmd/rHfsvBXxSxPX9A0Vk+MD98jGDaeL45FbhUOnCdA0gDhql7+Inrmp/b7heRpuSGj3BmgsAZBxZPB8NUdiEX/W6zSIm7KA8+G04zz8dayR6x+nnsAAY2GV4Tan2Bk0M+RQh8bVzHlbCAXqXA71qbLn7rI8P+goqkZfmJhE6AXFqOTtMptnJirX/RSJwcEzfkmlgEK/yvu9976VkhyjIqSXdDDxuY6kN2fbjzpZwUuvHKBTBDd0Wuf8f2U3wl7hfyJFY//EvcK995e9xyCAMKtwdixV/FsVoTxsthBpcQXY4QQCEOz37XCfl4tV1sKfDLbSc7AAkSrg=
services:
- docker
sudo: true
install:
- make setup-ci
script:
- make test
after_success: bash after-success.sh
